@url = http://localhost:8080/api/securityClearance

###

GET {{url}} HTTP/1.1

###

POST  {{url}} HTTP/1.1
Content-Type: application/json

{
    "name": "Testing"

}

###

PUT {{url}}/10 HTTP/1.1
Content-Type: application/json

{
        "name": "Testing2"

}

###

DELETE {{url}}/10 HTTP/1.1